import sys
import matplotlib
matplotlib.use('Agg')
from matplotlib import pyplot as plt

reference = 'AAGGTTAATAGGGAAACACGATAGAATCCGAACAGCACCTGTAAAACGACGGCCAGTGAATTGTAATACGACTCACTATAGGGCGAATTGGGCCCGACGTCGCATGCTCCCGGCCGCCATGGCGGCCGCGGGAATTCGATTAAGTCAGACTCCCTTACAACACTTATGGTGAGACGACAGTTGGGTGGCCGCGCCTCATTGGAGATAACAGCCATCCTGATCCGCTGCGGTAAAACGTATATTCTCGATCTTTAACCAGTAGGTTTGGCAGTGAAGTTAGCAAGTACCCCTATGAACAATTCAAATGGGGACAAAATCCATGCTCTGTACGGAAGAGTTCCTAGCGCAAAGGAGGACGGCACTACATTATAGCTGGAATGCCTAAGCGACGCGAACCGAGGGTCTTGATACACGTCACACATGATGACATATCCCAGATTCGGGAAATAGTTTATTGAGTGGACCTGGCGAGCCGGGCGGGGGCTACCTTCGTAGATGTTTCTTAATCGTGCGTGGTATTACGCTCAGTCCGATAGACACCGGAGCTTTCGACCGTTGACCAAGCCTTGTGGGCAATCACGGGTTGCATCGCATACTAATTTAGAGAGGTGCTTCTAGTCGGCGTTACTCGTTCTGCACAGTATCACTAGTGAATTCGCGGCCGCCTGCAGGTCGACCATATGGGAGAGCTCCCAACGCGTTGGATGCATAGCTTGAGTATTCTATAGTGTCACCTAAATAGCTTGGCGTAATCATGGTCATAGCTGTTTCCTG'

f = open(sys.argv[1],'r')

pos2events = {}

for line in f:

	splitLine = line.rstrip().split(' ')
	position = splitLine[0]
	if position not in pos2events:
		pos2events[position] = []
	else:
		pos2events[position] += map(float,splitLine[1:])
f.close()

for i, key in enumerate(pos2events):
	
	plt.figure(i)
	plt.hist( pos2events[key], 100 )
	plt.xlabel('pA')
	plt.ylabel('Count')
	plt.title( reference[int(key):int(key)+5] )
	plt.savefig( reference[int(key):int(key)+5] + '.png' )
	plt.close()
